spring:
  datasource:
      #无需指定，除非系统无法自动识别
      driverClassName: com.mysql.jdbc.Driver
      jdbcurl: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      #连接只读数据库时配置为true， 保证安全
      readOnly: false
      #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connectionTimeout: 30000
      #一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idleTimeout: 600000
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maxLifetime: 1800000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximumPoolSize: 15

  redis:
    # Redisson settings
    #path to redisson.yaml or redisson.json
#    redisson:
#      config: classpath:application-redisson.yml
    database: 1
    password: xbz_redis@2019
    timeout: 15000
    mode: single
    #连接池配置
    pool:
      max-idle: 16
      min-idle: 8
      max-active: 8
      max-wait: 3000
      conn-timeout: 3000
      so-timeout: 3000
      size: 10
    #单机配置
    single:
      address: 47.110.84.21:6379
    #集群配置
    cluster:
      scan-interval: 2000
      nodes:
      read-mode: SLAVE
      retry-attempts: 3
      failed-attempts: 3
      slave-connection-pool-size: 64
      master-connection-pool-size: 64
      retry-interval: 1500
    #哨兵配置
    sentinel:
      master: business-master
      nodes:
      master-onlyWrite: true
      fail-max: 3


