spring:
    application:
        name: study
    profiles:
        active: dev
    #session store type使用来存放session的存储方式，目前Spring boot中只支持redis方式
    #由于本应用暂无需将session放入redis的需求，故这里就可以将session store type设置为none
    session:
        store-type: none
#    rabbitmq:
#      host: 127.0.0.1
#      port: 5672
#      username: guest
#      password: guest

server:
    port: 9090

swagger.enabled: true

scheduling.enabled: false

logging:
    level:
        com.dzr.study: debug
#    file: /home/wwwlogs/${spring.application.name}.log
    config: classpath:logback.xml


